version: "2"
services:
    app:
        container_name: server
        restart: always
        build: .
        ports:
            - "3000:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./mongo_data:/data/db
        ports:
            - "27017:27017"
